<?php

return [
    "Mage2\\Address\\"          => base_path('/modules/base/Mage2/Address'),
    "Mage2\\Attribute\\"        => base_path('/modules/base/Mage2/Attribute'),
    "Mage2\\Auth\\"             => base_path('/modules/base/Mage2/Auth'),
    "Mage2\\Cart\\"             => base_path('/modules/base/Mage2/Cart'),
    "Mage2\\Checkout\\"         => base_path('/modules/base/Mage2/Checkout'),
    "Mage2\\Catalog\\"          => base_path('/modules/base/Mage2/Catalog'),
    "Mage2\\Common\\"           => base_path('/modules/base/Mage2/Common'),
    "Mage2\\Configuration\\"    => base_path('/modules/base/Mage2/Configuration'),
    "Mage2\\ContactUs\\"        => base_path('/modules/base/Mage2/ContactUs'),
    "Mage2\\Dashboard\\"        => base_path('/modules/base/Mage2/Dashboard'),
    "Mage2\\FreeShipping\\"     => base_path('/modules/base/Mage2/FreeShipping'),
    "Mage2\\Install\\"          => base_path('/modules/base/Mage2/Install'),
    "Mage2\\Order\\"            => base_path('/modules/base/Mage2/Order'),
    "Mage2\\Page\\"             => base_path('/modules/base/Mage2/Page'),
    "Mage2\\Paypal\\"           => base_path('/modules/base/Mage2/Paypal'),
    "Mage2\\Pickup\\"           => base_path('/modules/base/Mage2/Pickup'),
    "Mage2\\Review\\"           => base_path('/modules/base/Mage2/Review'),
    "Mage2\\TaxClass\\"         => base_path('/modules/base/Mage2/TaxClass'),
    "Mage2\\Theme\\"            => base_path('/modules/base/Mage2/Theme'),
    "Mage2\\User\\"             => base_path('/modules/base/Mage2/User'),
    "Mage2\\Wishlist\\"         => base_path('/modules/base/Mage2/Wishlist'),
];
