@include('template.text',['key' => 'title','label' => 'Title'])
@include('template.text',['key' => 'slug','label' => 'Slug'])
@include('template.editor',['key' => 'content','label' => 'Content'])
@include('template.text',['key' => 'meta_title','label' => 'Meta Title'])
@include('template.text',['key' => 'meta_description','label' => 'Meta Description'])